# Generated by Django 5.1.1 on 2024-09-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='minor', max_length=10),
        ),
    ]
