# Generated by Django 5.1.1 on 2024-09-08 18:28

import django_google_maps.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='0.0,0.0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10),
        ),
    ]
