# Generated by Django 5.1.1 on 2024-09-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_address_post_geolocation_alter_post_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='geolocation',
        ),
    ]
